(* Copyright (c) INRIA and Microsoft Corporation. All rights reserved. *)
(* Licensed under the Apache 2.0 and MIT Licenses. *)

(** Writing out JavaScript files generated by CStarToJS. *)

let js_name f = f ^ ".js"

let write_file (name, doc) =
  let base = if !Options.tmpdir <> "" then !Options.tmpdir else "." in
  let filename = Driver.((^^)) base (js_name name) in
  Utils.with_open_out_bin filename (fun oc ->
    PPrint.ToChannel.pretty 0.95 100 oc doc
  );
  filename

let write_all files =
  Driver.maybe_create_output_dir ();
  let filenames = List.map write_file files in
  if Options.debug "js-filenames" then
    KPrint.bfprintf stdout "INFO: wrote %d files\n%s\n" (List.length filenames)
      (String.concat "\n" filenames)
